### ISSUE TITLE
Content goes off the page (and prevents scrollbars?)

### ISSUE THREAD

**Issue by amirmc** [mirage/mirage-decks#33]
Bug report by email.  I can't repro this on my browsers but there's a screenshot attached.

> Haven't managed to reproduce the FF
> display issues again, but here is an example of the "no scrollbars"
> problem in Chrome (well, Chromium, really). It's all the more annoying
> since the arrows are hijacked by the page. With FF + Vimperator, it is
> possible to scroll with 'J/K' and see the rest of the text.

![chromium_presentation_issue](https://cloud.githubusercontent.com/assets/121855/5518441/3b898940-8920-11e4-901d-7a7136f49534.png)

**Comment by mor1** [comment]
re font-- just had a look at this, and it looks like there's some url routing weirdness that's causing the `@url()` entries that are supposed to point to the embedded fonts to fail. i'll put this on the todo list to fix. (might be a few days as have a lot to catch up on after the holiday and moving jobs :)

re performance-- absolutely, yes. could you create an issue requesting this please?

**Comment by Emm** [comment]
@mor1 done

**Comment by mor1** [comment]
@Emm finally had a look at this. our (that is, my) use of `@font-face` was completely and utterly broken. i suspect it was working for me due to happy accident (my mac has `PT Sans` and `PT Sans Narrow` fonts that matched).

i think i've now fixed this -- at least, i see the webfont being fetched from the server as i expect now. i'll merge the patch once travis completes the build, and then will have to make the rebuilt site live. will pingback here when done. sorry about the delay...

**Comment by Emm** [comment]
No worries.

**Comment by mor1** [comment]
@Emm Argh sorry, forgot to pingback! I think this is now fixed, so closing. Please reopen if you see the problem again!
